import { expect, test } from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';

test.describe('FastBlocks UI accessibility', () => {
  test.beforeEach(async ({ page }) => {
    await page.goto('/demo/demo.html');
    await page.waitForLoadState('networkidle');
  });

  test('has no automatically detectable accessibility violations', async ({ page }) => {
    const scan = await new AxeBuilder({ page })
      .withTags(['wcag2a', 'wcag2aa', 'wcag21a', 'wcag21aa'])
      .analyze();

    expect(scan.violations).toEqual([]);
  });
});

// Both demo pages are axe-clean -- ZERO violations, at every width below,
// measured 2026-07-31 in Chrome 150 with axe-core 4.11's full default ruleset
// (no `withTags` narrowing, unlike the scan above). So assert zero: the
// strongest form of this gate.
//
// It did not start here. The baseline carried `landmark-unique` (two showcase
// navbars both taking `navbar()`'s default "main navigation", so two landmarks
// shared one accessible name) and `scrollable-region-focusable` (three scroll
// containers with no focusable descendant: the escaped-markup `<pre>`, the
// container-query comparison strip, and `.ui-table__container` -- the last a
// real defect in the shipped library, where a keyboard user could not scroll a
// wide table at all). All were fixed rather than allowlisted. If this gate ever
// needs an allowlist again, that is a regression to fix, not a list to grow.
//
// Swept across the breakpoint because the shell changes shape at 1024px, and
// the two shapes are not equally audited. Below it the table of contents is an
// off-canvas `[popover]` drawer computing `display: none`, which axe skips
// entirely; above it the same node is an in-flow sticky column. Measured with
// `AxeBuilder.include('#site-nav')`: 0 nodes evaluated at 768px, 91 nodes
// across 10 rules at 1280px. A scan at one width alone leaves one of the two
// renderings unaudited.
//
// The narrow widths pull their weight in the other direction: reintroducing
// the `.ui-table__container` `scrollable-region-focusable` defect fails ONLY at
// 375px, because the table does not overflow at wider viewports.
//
// `demo.html` is hand-written and `index.html` is generated by
// scripts/build_demo.py from the real helpers, so both are scanned -- a helper
// could regress the generated page without touching the hand-written one.
for (const page_ of ['/demo/demo.html', '/demo/index.html']) {
  for (const width of [375, 768, 1024, 1280]) {
    test(`${page_} has no axe violations at ${width}px`, async ({ page }) => {
      await page.setViewportSize({ width, height: 900 });
      await page.goto(page_);
      await page.waitForLoadState('networkidle');

      const results = await new AxeBuilder({ page }).analyze();

      expect(results.violations).toEqual([]);
    });
  }
}

// Emulation sweep: the demo must remain axe-clean under each media
// preference that fastblocks-ui explicitly opts into. The existing
// `prefers-reduced-motion` emulation handles it for that rule, but the
// library also calls `matchMedia('(prefers-reduced-transparency: reduce)')`
// and `matchMedia('(forced-colors: active)')` from the effects modules,
// so a regression in the CSS that inadvertently hides or recolours
// content under those modes would only surface here. The `forced-colors`
// emulation in particular is hostile to `color-mix()` and `oklch()`-based
// tokens, so this is a real risk surface.
const EMULATIONS = [
  { name: 'prefers-reduced-motion', media: { reducedMotion: 'reduce' } },
  { name: 'prefers-reduced-transparency', media: {} },
  { name: 'forced-colors', media: { forcedColors: 'active' } },
];

for (const emu of EMULATIONS) {
  test(`demo.html axe-clean under ${emu.name}`, async ({ page }) => {
    // `prefers-reduced-transparency` has no native Playwright emulation
    // (1.62); shim matchMedia so the page's CSS sees it as active.
    if (emu.name === 'prefers-reduced-transparency') {
      await page.emulateMedia(emu.media);
      await page.addInitScript(() => {
        const original = window.matchMedia;
        window.matchMedia = (query) => {
          const result = original.call(window, query);
          if (query === '(prefers-reduced-transparency: reduce)') {
            Object.defineProperty(result, 'matches', {
              value: true,
              configurable: true,
            });
          }
          return result;
        };
      });
    } else {
      await page.emulateMedia(emu.media);
    }
    await page.goto('/demo/demo.html');
    await page.waitForLoadState('networkidle');

    const results = await new AxeBuilder({ page }).analyze();
    expect(results.violations).toEqual([]);
  });
}

// Per-rule axe coverage for the components introduced in the UI vocabulary
// expansion. The default AxeBuilder scan above catches most issues, but
// these rules are structural: they depend on a component being rendered
// in a specific shape (menu/menuitem, listbox/option, combobox+listbox,
// role="img" avatar, popover trigger). Fixtures live at
// tests/e2e/fixtures/axe-component-rules.html and the four sub-tests
// each scope AxeBuilder to the relevant DOM slice so a failure names
// the actual missing structure.
const AXE_RULE_FIXTURE = '/tests/e2e/fixtures/axe-component-rules.html';

test.describe('new component axe rules', () => {
  test.beforeEach(async ({ page }) => {
    await page.goto(AXE_RULE_FIXTURE);
    await page.waitForLoadState('networkidle');
  });

  test('aria-required-children: menus contain menuitem, listboxes contain option', async ({
    page,
  }) => {
    const results = await new AxeBuilder({ page })
      .include('nav[data-axe-menu]')
      .include('[data-axe-listbox]')
      .withRules(['aria-required-children'])
      .analyze();
    expect(results.violations).toEqual([]);
  });

  test('aria-required-parent: listbox is a child of combobox', async ({ page }) => {
    const results = await new AxeBuilder({ page })
      .include('[data-axe-combobox]')
      .withRules(['aria-required-parent'])
      .analyze();
    expect(results.violations).toEqual([]);
  });

  test('role-img-alt: avatar with role="img" has non-empty accessible name', async ({
    page,
  }) => {
    const results = await new AxeBuilder({ page })
      .include('[data-axe-avatar]')
      .withRules(['role-img-alt'])
      .analyze();
    expect(results.violations).toEqual([]);
  });

  test('aria-allowed-attr: aria-expanded only on allowed roles', async ({ page }) => {
    const results = await new AxeBuilder({ page })
      .include('[data-axe-popover-trigger]')
      .withRules(['aria-allowed-attr'])
      .analyze();
    expect(results.violations).toEqual([]);
  });
});
