import { expect, test } from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';

test.describe('FastBlocks UI accessibility', () => {
  test.beforeEach(async ({ page }) => {
    await page.goto('/demo/demo.html');
    await page.waitForLoadState('networkidle');
  });

  test('has no automatically detectable accessibility violations', async ({ page }) => {
    const scan = await new AxeBuilder({ page })
      .withTags(['wcag2a', 'wcag2aa', 'wcag21a', 'wcag21aa'])
      .analyze();

    expect(scan.violations).toEqual([]);
  });
});

// Both demo pages are axe-clean -- ZERO violations, at every width below,
// measured 2026-07-31 in Chrome 150 with axe-core 4.11's full default ruleset
// (no `withTags` narrowing, unlike the scan above). So assert zero: the
// strongest form of this gate.
//
// It did not start here. The baseline carried `landmark-unique` (two showcase
// navbars both taking `navbar()`'s default "main navigation", so two landmarks
// shared one accessible name) and `scrollable-region-focusable` (three scroll
// containers with no focusable descendant: the escaped-markup `<pre>`, the
// container-query comparison strip, and `.ui-table-container` -- the last a
// real defect in the shipped library, where a keyboard user could not scroll a
// wide table at all). All were fixed rather than allowlisted. If this gate ever
// needs an allowlist again, that is a regression to fix, not a list to grow.
//
// Swept across the breakpoint because the shell changes shape at 1024px, and
// the two shapes are not equally audited. Below it the table of contents is an
// off-canvas `[popover]` drawer computing `display: none`, which axe skips
// entirely; above it the same node is an in-flow sticky column. Measured with
// `AxeBuilder.include('#site-nav')`: 0 nodes evaluated at 768px, 91 nodes
// across 10 rules at 1280px. A scan at one width alone leaves one of the two
// renderings unaudited.
//
// The narrow widths pull their weight in the other direction: reintroducing
// the `.ui-table-container` `scrollable-region-focusable` defect fails ONLY at
// 375px, because the table does not overflow at wider viewports.
//
// `demo.html` is hand-written and `index.html` is generated by
// scripts/build_demo.py from the real helpers, so both are scanned -- a helper
// could regress the generated page without touching the hand-written one.
for (const page_ of ['/demo/demo.html', '/demo/index.html']) {
  for (const width of [375, 768, 1024, 1280]) {
    test(`${page_} has no axe violations at ${width}px`, async ({ page }) => {
      await page.setViewportSize({ width, height: 900 });
      await page.goto(page_);
      await page.waitForLoadState('networkidle');

      const results = await new AxeBuilder({ page }).analyze();

      expect(results.violations).toEqual([]);
    });
  }
}
