#!/usr/bin/env python3
"""Generate FastBlocks UI component documentation from the manifest."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parents[1]
MANIFEST_PATH = REPO_ROOT / "fastblocks_ui" / "manifest.json"
DOCS_DIR = REPO_ROOT / "docs" / "components"


def load_manifest() -> dict[str, Any]:
    """Load the supported component manifest."""
    return json.loads(MANIFEST_PATH.read_text(encoding="utf-8"))


def component_by_name(manifest: dict[str, Any], name: str) -> dict[str, Any]:
    """Return component metadata by component name."""
    for component in manifest["components"]:
        if component["name"] == name:
            return component
    available = ", ".join(component["name"] for component in manifest["components"])
    raise SystemExit(f"Unknown component {name!r}. Available components: {available}")


def example_markup(component: dict[str, Any]) -> str:
    """Return a small HTML example for a manifest component."""
    class_name = component["class_name"]
    name = component["name"]

    if name == "input":
        return '<input class="ui-input" name="email" type="email" autocomplete="email">'
    if name == "select":
        return (
            '<select class="ui-select" name="status">\n'
            '  <option value="active">Active</option>\n'
            '  <option value="paused">Paused</option>\n'
            "</select>"
        )
    if name == "checkbox":
        return (
            '<label class="ui-checkbox">\n'
            '  <input type="checkbox" name="enabled" checked>\n'
            "  Enabled\n"
            "</label>"
        )
    if name == "dialog":
        return (
            '<dialog class="ui-dialog" id="settings-dialog">\n'
            '  <form method="dialog">\n'
            "    <p>Dialog content</p>\n"
            '    <button class="ui-button">Close</button>\n'
            "  </form>\n"
            "</dialog>"
        )
    if name == "tabs":
        return (
            '<div class="ui-tabs" data-ui-tabs>\n'
            '  <div role="tablist">\n'
            '    <button role="tab" aria-selected="true" aria-controls="panel-a">'
            "Overview</button>\n"
            "  </div>\n"
            '  <section id="panel-a" role="tabpanel">Overview content</section>\n'
            "</div>"
        )
    if name == "menu":
        return (
            '<nav class="ui-menu" aria-label="Section">\n'
            '  <a href="/overview" class="is-active">Overview</a>\n'
            '  <a href="/settings">Settings</a>\n'
            "</nav>"
        )
    if name == "alert":
        return '<div class="ui-alert is-info" role="status">Saved.</div>'
    if name == "button":
        return '<button class="ui-button is-primary" type="button">Save</button>'
    if name == "validation_summary":
        return (
            '<div class="ui-alert is-danger ui-validation-summary" role="alert">\n'
            '  <strong class="ui-validation-summary__title">Please correct the errors below.</strong>\n'
            '  <ul class="ui-validation-summary__list">\n'
            '    <li><a href="#email">Email is required.</a></li>\n'
            "  </ul>\n"
            "</div>"
        )

    return f'<div class="{class_name}">{name.title()} content</div>'


def generate_component_docs(component: dict[str, Any]) -> str:
    """Generate markdown documentation for a component."""
    helper = component.get("helper", component["name"])
    return f"""# {component["name"]}

{component["description"]}

## Usage

```html
{example_markup(component)}
```

## Helper

The `{helper}()` helper emits this component's canonical server-rendered markup.
It accepts normal HTML attributes where supported and keeps output compatible
with Jinja, FastBlocks, and htmx fragment swaps.

## Component Contract

- Public class: `{component["class_name"]}`
- Rendering model: standard HTML with `ui-*` classes
- JavaScript model: optional progressive enhancement only
- htmx model: state stays in server-rendered markup

Generated by `scripts/generate-docs.py`.
"""


def write_all(manifest: dict[str, Any]) -> None:
    """Generate docs for every manifest component."""
    DOCS_DIR.mkdir(parents=True, exist_ok=True)
    for component in manifest["components"]:
        path = DOCS_DIR / f"{component['name']}.md"
        path.write_text(generate_component_docs(component), encoding="utf-8")
        print(f"Generated {path.relative_to(REPO_ROOT)}")


def main() -> None:
    """Run the documentation generator."""
    parser = argparse.ArgumentParser(
        description="Generate FastBlocks UI docs from fastblocks_ui/manifest.json"
    )
    parser.add_argument("component", nargs="?", help="Component name, e.g. button")
    parser.add_argument("--all", action="store_true", help="Write all component docs")
    parser.add_argument("--list", action="store_true", help="List components")
    args = parser.parse_args()

    manifest = load_manifest()

    if args.list:
        for component in manifest["components"]:
            print(component["name"])
        return

    if args.all:
        write_all(manifest)
        return

    if args.component:
        print(generate_component_docs(component_by_name(manifest, args.component)))
        return

    parser.print_help()
    sys.exit(1)


if __name__ == "__main__":
    main()
