#!/usr/bin/env python3
"""Generate a FastBlocks UI token reference stylesheet."""

from __future__ import annotations

TOKENS = {
    "color-primary": "#4f46e5",
    "color-info": "#06b6d4",
    "color-success": "#22c55e",
    "color-warning": "#eab308",
    "color-danger": "#ef4444",
    "color-surface": "#ffffff",
    "color-text": "#374151",
    "radius-sm": "4px",
    "radius-md": "6px",
    "radius-lg": "8px",
    "space-1": "0.25rem",
    "space-2": "0.5rem",
    "space-3": "0.75rem",
    "space-4": "1rem",
    "space-5": "1.5rem",
    "space-6": "2rem",
    "space-8": "3rem",
    "space-10": "4rem",
    "space-12": "6rem",
}


def generate_tokens_css() -> str:
    """Return CSS for the package's public token namespace."""
    lines = [
        "/* FastBlocks UI token reference */",
        "/* Generated by scripts/generate-css-variables.py */",
        "@layer tokens {",
        "  :root {",
    ]
    for name, value in TOKENS.items():
        lines.append(f"    --ui-{name}: {value};")
    lines.extend(["  }", "}"])
    return "\n".join(lines) + "\n"


def main() -> None:
    """Print generated token CSS to stdout."""
    print(generate_tokens_css(), end="")


if __name__ == "__main__":
    main()
